apiVersion: v1
kind: Service
metadata:
  name: phoenix-service
  namespace: phoenix
spec:
  selector:
    app: phoenix
  ports:
    - name: ui
      port: 6006
      targetPort: 6006
    - name: otlp
      port: 4317
      targetPort: 4317
  type: ClusterIP
