apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - envoy-proxy.yaml
  - gateway-class.yaml
  - gateway-config.yaml
  - gateway.yaml
  - client-traffic-policy.yaml
