apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-d-router
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-d-router
  template:
    metadata:
      labels:
        app: llm-d-router
    spec:
      serviceAccountName: epp-sa
      containers:
        - name: router
          image: registry.k8s.io/gateway-api-inference-extension/epp:v1.5.0
          args:
            - "/epp"
            - "--pool-name=prefix-scorer-pool"
            - "--pool-namespace=vllm"
            - "--grpc-port=9000"
            - |
              --config-text=apiVersion: inference.networking.x-k8s.io/v1alpha1
              kind: EndpointPickerConfig
              plugins:
              - type: prefix-cache-scorer
                name: prefix-cache-scorer
              - type: queue-scorer
                name: queue-scorer
              schedulingProfiles:
              - name: default
                plugins:
                - pluginRef: prefix-cache-scorer
                  weight: 10
                - pluginRef: queue-scorer
                  weight: 5
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: llm-d-router
  namespace: vllm
spec:
  selector:
    app: llm-d-router
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-d-router-noprefix
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-d-router-noprefix
  template:
    metadata:
      labels:
        app: llm-d-router-noprefix
    spec:
      serviceAccountName: epp-sa
      containers:
        - name: router
          image: registry.k8s.io/gateway-api-inference-extension/epp:v1.5.0
          args:
            - "/epp"
            - "--pool-name=generic-pool"
            - "--pool-namespace=vllm"
            - "--grpc-port=9000"
            - |
              --config-text=apiVersion: inference.networking.x-k8s.io/v1alpha1
              kind: EndpointPickerConfig
              plugins:
              - type: queue-scorer
                name: queue-scorer
              schedulingProfiles:
              - name: default
                plugins:
                - pluginRef: queue-scorer
                  weight: 1
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: llm-d-router-noprefix
  namespace: vllm
spec:
  selector:
    app: llm-d-router-noprefix
  ports:
    - port: 9000
      targetPort: 9000
